version: "3.8"
services:
  notenexus_ai:
    image: johnkristan01/notenexus_ai:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment: 
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network


  nginx:
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        - /etc/letsencrypt:/etc/letsencrypt:ro
      networks:
        - app-network

networks:
  app-network:
    driver: bridge