version: "3.8"
services:
  notenexus_ai:
    image: johnkristan01/notenexus_ai:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment: 
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      - app-network


  nginx:
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - app
      networks:
        - app-network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 10s
        timeout: 5s
        retries: 3

networks:
  app-network:
    driver: bridge