name: Deploy NoteNexus AI to Amazon EC2 (Amazon Linux 2)
on:
  push:
    branches: [main]
env:
  SERVER_DIR: /home/${{ secrets.EC2_USER }}/server
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_KEY: ${{ secrets.EC2_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: 🧱 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: TEMP Echo Docker Hub secrets unmasked
        run: |
            echo "Username length: ${#DOCKER_HUB_USERNAME}"
            echo "Password length: ${#DOCKER_HUB_PASSWORD}"

      # DOCKER BUILDING AND PUSHING TO DOCKER HUB REGISTRY
      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}


      - name: Create .env File for Docker Compose Environment
        run: |
          cat <<'EOF' > .env
          DATABASE_URL=$DATABASE_URL
          OPENAI_API_KEY=$OPENAI_API_KEY
          EOF

      - name: Build & Push Docker Image using Docker Compose
        run: |
            docker compose -f docker-compose.local.yml build --no-cache
            docker compose -f docker-compose.local.yml push 

      - name: 🏗️ Ensure server directory exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ${{ env.SERVER_DIR }}

      - name: 🔍 Debug file presence
        run: |
          ls -lah
          ls -lah docker-compose.prod.yml || echo "Missing: docker-compose.prod.yml"
          ls -lah alembic.ini || echo "Missing: alembic.ini"


      # EC2 INSTANCE DEPLOYMENT SETUP
      - name: 📂 Upload Compose & Config Files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
            host: ${{ env.EC2_HOST }}
            username: ${{ env.EC2_USER }}
            key: ${{ env.EC2_KEY }}
            source: "docker-compose.prod.yml,alembic.ini,default.conf"
            target: ${{ env.SERVER_DIR }}



      - name: 🚀 Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ env.EC2_HOST }}
            username: ${{ env.EC2_USER }}
            key: ${{ env.EC2_KEY }}
            envs: DOCKER_HUB_USERNAME,DOCKER_HUB_PASSWORD,DATABASE_URL,OPENAI_API_KEY,SERVER_DIR
            script: |
              set -e
              cd $SERVER_DIR

              echo "🟨 Logging in to Docker..."
              echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

              echo "📄 Writing .env file..."
              cat <<EOF > .env
              DATABASE_URL=$DATABASE_URL
              OPENAI_API_KEY=$OPENAI_API_KEY
              EOF


              echo "📄 Checking Files inside EC2"
              ls -lah

              echo "📄 Viewing .env file"
              cat .env

              echo "🧼 Stopping old containers (if any)..."
              docker-compose -f docker-compose.prod.yml down || true
              
              echo "⬇️ Pulling latest images..."
              docker-compose -f docker-compose.prod.yml pull

              echo "🚀 Starting containers..."
              docker-compose -f docker-compose.prod.yml up -d --remove-orphans

              echo "✅ Checking container status..."
              docker-compose -f docker-compose.prod.yml ps

              echo "📜 Recent logs:"
              docker-compose -f docker-compose.prod.yml logs --tail=50

